[supervisord]
logfile_maxbytes=1MB
logfile_backups=2
nodaemon=true

[program:config_listener]
command=/usr/bin/python3 /usr/bin/config_listener.py
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/var/log/supervisor/config_listener.stdout.log
stderr_logfile=/var/log/supervisor/config_listener.stderr.log

[program:cpu_collector]
command=/usr/bin/python3 /usr/bin/cpu_collector.py
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/var/log/supervisor/cpu_collector.stdout.log
stderr_logfile=/var/log/supervisor/cpu_collector.stderr.log
