#name                          lanes    alias            speed  autoneg   fec   index
Ethernet0                         0    fiftyGigE0      	50000   on     rs     1  
Ethernet1                         1    fiftyGigE1      	50000   on     rs     2  
Ethernet2                         2    fiftyGigE2      	50000   on     rs     3  
Ethernet3                         3    fiftyGigE3      	50000   on     rs     4  
Ethernet4                         4    fiftyGigE4      	50000   on     rs     5  
Ethernet5                         5    fiftyGigE5      	50000   on     rs     6  
Ethernet6                         6    fiftyGigE6      	50000   on     rs     7  
Ethernet7                         7    fiftyGigE7      	50000   on     rs     8
Ethernet8                         8    fiftyGigE8      	50000   on     rs     9  
Ethernet9                         9    fiftyGigE9      	50000   on     rs     10  
Ethernet10                        10   fiftyGigE10      50000   on     rs     11  
Ethernet11                        11   fiftyGigE11     	50000   on     rs     12  
Ethernet12                        12   fiftyGigE12     	50000   on     rs     13 
Ethernet13                        13   fiftyGigE13     	50000   on     rs     14 
Ethernet14                        14   fiftyGigE14     	50000   on     rs     15 
Ethernet15                        15   fiftyGigE15     	50000   on     rs     16
Ethernet16                        16   fiftyGigE16     	50000   on     rs     17 
Ethernet17                        17   fiftyGigE17     	50000   on     rs     18 
Ethernet18                        18   fiftyGigE18     	50000   on     rs     19 
Ethernet19                        19   fiftyGigE19     	50000   on     rs     20 
Ethernet20                        20   fiftyGigE20     	50000   on     rs     21 
Ethernet21                        21   fiftyGigE21     	50000   on     rs     22 
Ethernet22                        22   fiftyGigE22     	50000   on     rs     23 
Ethernet23                        23   fiftyGigE23     	50000   on     rs     24
Ethernet24                        24   fiftyGigE24     	50000   on     rs     25 
Ethernet25                        25   fiftyGigE25     	50000   on     rs     26 
Ethernet26                        26   fiftyGigE26     	50000   on     rs     27 
Ethernet27                        27   fiftyGigE27     	50000   on     rs     28