#name                          lanes    alias            speed  autoneg   fec   index
Ethernet0                         0    twenty5GigE0     25000   on     rs     1  
Ethernet1                         1    twenty5GigE1     25000   on     rs     2  
Ethernet2                         2    twenty5GigE2     25000   on     rs     3  
Ethernet3                         3    twenty5GigE3     25000   on     rs     4  
Ethernet4                         4    twenty5GigE4     25000   on     rs     5  
Ethernet5                         5    twenty5GigE5     25000   on     rs     6  
Ethernet6                         6    twenty5GigE6     25000   on     rs     7  
Ethernet7                         7    twenty5GigE7     25000   on     rs     8
Ethernet8                         8    twenty5GigE8     25000   on     rs     9  
Ethernet9                         9    twenty5GigE9     25000   on     rs     10  
Ethernet10                        10   twenty5GigE10    25000   on     rs     11  
Ethernet11                        11   twenty5GigE11    25000   on     rs     12  
Ethernet12                        12   twenty5GigE12    25000   on     rs     13 
Ethernet13                        13   twenty5GigE13    25000   on     rs     14 
Ethernet14                        14   twenty5GigE14    25000   on     rs     15 
Ethernet15                        15   twenty5GigE15    25000   on     rs     16
Ethernet16                        16   twenty5GigE16    25000   on     rs     17 
Ethernet17                        17   twenty5GigE17    25000   on     rs     18 
Ethernet18                        18   twenty5GigE18    25000   on     rs     19 
Ethernet19                        19   twenty5GigE19    25000   on     rs     20 
Ethernet20                        20   twenty5GigE20    25000   on     rs     21 
Ethernet21                        21   twenty5GigE21    25000   on     rs     22 
Ethernet22                        22   twenty5GigE22    25000   on     rs     23 
Ethernet23                        23   twenty5GigE23    25000   on     rs     24
Ethernet24                        24   fiftyGigE24     	50000   on     rs     25 
Ethernet25                        25   fiftyGigE25     	50000   on     rs     26 
Ethernet26                        26   fiftyGigE26     	50000   on     rs     27 
Ethernet27                        27   fiftyGigE27     	50000   on     rs     28
Ethernet28                        28   fiftyGigE28 		50000   on     rs     29