# docker image for cpu-monitor agent

DOCKER_CPU_MONITOR_STEM = docker-cpu-monitor
docker_cpu_monitor = $(DOCKER_CPU_MONITOR_STEM)
DOCKER_CPU_MONITOR = $(DOCKER_CPU_MONITOR_STEM).gz
DOCKER_CPU_MONITOR_DBG = $(DOCKER_CPU_MONITOR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_CPU_MONITOR)_PATH = $(DOCKERS_PATH)/$(DOCKER_CPU_MONITOR_STEM)

$(DOCKER_CPU_MONITOR)_PACKAGE_NAME = cpu-monitor
$(DOCKER_CPU_MONITOR)_DEPENDS += $(CPU_MONITOR)

$(DOCKER_CPU_MONITOR)_DEPENDS += $(PYTHON_SWSSCOMMON)
$(DOCKER_CPU_MONITOR)_DBG_DEPENDS = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_DEPENDS)

$(DOCKER_CPU_MONITOR)_DBG_IMAGE_PACKAGES = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_CPU_MONITOR)_LOAD_DOCKERS += $(DOCKER_SWSS_LAYER_BOOKWORM)


$(DOCKER_CPU_MONITOR)_VERSION = 1.0.0

$(DOCKER_CPU_MONITOR)_WARM_SHUTDOWN_BEFORE = syncd
$(DOCKER_CPU_MONITOR)_WARM_SHUTDOWN_AFTER = swss
$(DOCKER_CPU_MONITOR)_FAST_SHUTDOWN_BEFORE = syncd
$(DOCKER_CPU_MONITOR)_FAST_SHUTDOWN_AFTER = swss

SONIC_DOCKER_IMAGES += $(DOCKER_CPU_MONITOR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_CPU_MONITOR)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_CPU_MONITOR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_CPU_MONITOR_DBG)

$(DOCKER_CPU_MONITOR)_CONTAINER_NAME = cpu-monitor
$(DOCKER_CPU_MONITOR)_RUN_OPT += -t --cap-add=NET_ADMIN
$(DOCKER_CPU_MONITOR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_CPU_MONITOR)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
$(DOCKER_CPU_MONITOR)_RUN_OPT += -v /host/warmboot:/var/warmboot

# $(DOCKER_CPU_MONITOR)_BASE_IMAGE_FILES += ...

$(DOCKER_CPU_MONITOR)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_CPU_MONITOR)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_CPU_MONITOR_DBG)
